format = """
[](green)\
$os\
$username\
[](bg:cyan fg:green)\
$directory\
[](fg:cyan bg:green)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:green bg:red)\
[](fg:red bg:blue)\
$docker_context\
$conda\
$pixi\
[ ](fg:blue)\
$time\
$git_branch\
$git_status\
$line_break$character"""

palette = 'color'
[palettes.color]
background = '#1b0c0c'
black = '#1b0c0c'
blue = '#494A46'
cursor = '#c6c2c2'
cyan = '#9E2017'
foreground = '#c6c2c2'
green = '#D01B0D'
magenta = '#F41203'
red = '#F82C04'
tabs = '#c6c2c2'
tabs-active = '#E9561A'
white = '#c6c2c2'
yellow = '#c6c2c2'
dim-black = '#1b0c0c'
dim-blue = '#494A46'
dim-cyan = '#9E2017'
dim-foreground = '#c6c2c2'
dim-green = '#D01B0D'
dim-magenta = '#F41203'
dim-red = '#F82C04'
dim-white = '#E9561A'
dim-yellow = '#c6c2c2'
light-black = '#494A46'
light-blue = '#9E2017'
light-cyan = '#D01B0D'
light-foreground = '#F41203'
light-green = '#F82C04'
light-magenta = '#E9561A'
light-red = '#c6c2c2'
light-white = '#494A46'
light-yellow = '#9E2017'


[os]
disabled = false
style = "bg:green fg:foreground"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:green fg:foreground"
style_root = "bg:green fg:foreground"
format = '[ $user ]($style)'

[directory]
style = "fg:foreground bg:cyan"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "


[nodejs]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[c]
symbol = " "
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[cpp]
symbol = " "
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[rust]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[golang]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[php]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[java]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[kotlin]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[haskell]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[python]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[docker_context]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $context) ](fg:#83a598 bg:green)]($style)'

[conda]
style = "bg:green"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:green)]($style)'

[pixi]
style = "bg:green"
format = '[[ $symbol( $version)( $environment) ](fg:foreground bg:green)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:background"
format = '[[  $time ](fg:foreground bg:background)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:magenta)'
error_symbol = '[](bold fg:blue)'
vimcmd_symbol = '[](bold fg:magenta)'
vimcmd_replace_one_symbol = '[](bold fg:white)'
vimcmd_replace_symbol = '[](bold fg:white)'
