format = """
[](green)\
$os\
$username\
[](bg:cyan fg:green)\
$directory\
[](fg:cyan bg:green)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:green bg:red)\
[](fg:red bg:blue)\
$docker_context\
$conda\
$pixi\
[ ](fg:blue)\
$time\
$git_branch\
$git_status\
$line_break$character"""

palette = 'color'
[palettes.color]
background = '#180b0a'
black = '#180b0a'
blue = '#AC3425'
cursor = '#c5c2c1'
cyan = '#BB4530'
foreground = '#c5c2c1'
green = '#D35F27'
magenta = '#C54E38'
red = '#BE5A42'
tabs = '#c5c2c1'
tabs-active = '#CE6148'
white = '#c5c2c1'
yellow = '#c5c2c1'
dim-black = '#180b0a'
dim-blue = '#AC3425'
dim-cyan = '#BB4530'
dim-foreground = '#c5c2c1'
dim-green = '#D35F27'
dim-magenta = '#C54E38'
dim-red = '#BE5A42'
dim-white = '#CE6148'
dim-yellow = '#c5c2c1'
light-black = '#AC3425'
light-blue = '#BB4530'
light-cyan = '#D35F27'
light-foreground = '#C54E38'
light-green = '#BE5A42'
light-magenta = '#CE6148'
light-red = '#c5c2c1'
light-white = '#AC3425'
light-yellow = '#BB4530'


[os]
disabled = false
style = "bg:green fg:foreground"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:green fg:foreground"
style_root = "bg:green fg:foreground"
format = '[ $user ]($style)'

[directory]
style = "fg:foreground bg:cyan"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "


[nodejs]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[c]
symbol = " "
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[cpp]
symbol = " "
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[rust]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[golang]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[php]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[java]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[kotlin]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[haskell]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[python]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[docker_context]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $context) ](fg:#83a598 bg:green)]($style)'

[conda]
style = "bg:green"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:green)]($style)'

[pixi]
style = "bg:green"
format = '[[ $symbol( $version)( $environment) ](fg:foreground bg:green)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:background"
format = '[[  $time ](fg:foreground bg:background)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:magenta)'
error_symbol = '[](bold fg:blue)'
vimcmd_symbol = '[](bold fg:magenta)'
vimcmd_replace_one_symbol = '[](bold fg:white)'
vimcmd_replace_symbol = '[](bold fg:white)'
