format = """
[](green)\
$os\
$username\
[](bg:cyan fg:green)\
$directory\
[](fg:cyan bg:green)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:green bg:red)\
[](fg:red bg:blue)\
$docker_context\
$conda\
$pixi\
[ ](fg:blue)\
$time\
$git_branch\
$git_status\
$line_break$character"""

palette = 'color'
[palettes.color]
background = '#0d1e1c'
black = '#0d1e1c'
blue = '#3F3C44'
cursor = '#c2c6c6'
cyan = '#6A5C4E'
foreground = '#c2c6c6'
green = '#625E59'
magenta = '#A05552'
red = '#97826B'
tabs = '#c2c6c6'
tabs-active = '#A59F92'
white = '#c2c6c6'
yellow = '#c2c6c6'
dim-black = '#0d1e1c'
dim-blue = '#3F3C44'
dim-cyan = '#6A5C4E'
dim-foreground = '#c2c6c6'
dim-green = '#625E59'
dim-magenta = '#A05552'
dim-red = '#97826B'
dim-white = '#A59F92'
dim-yellow = '#c2c6c6'
light-black = '#3F3C44'
light-blue = '#6A5C4E'
light-cyan = '#625E59'
light-foreground = '#A05552'
light-green = '#97826B'
light-magenta = '#A59F92'
light-red = '#c2c6c6'
light-white = '#3F3C44'
light-yellow = '#6A5C4E'


[os]
disabled = false
style = "bg:green fg:foreground"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:green fg:foreground"
style_root = "bg:green fg:foreground"
format = '[ $user ]($style)'

[directory]
style = "fg:foreground bg:cyan"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "


[nodejs]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[c]
symbol = " "
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[cpp]
symbol = " "
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[rust]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[golang]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[php]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[java]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[kotlin]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[haskell]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[python]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[docker_context]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $context) ](fg:#83a598 bg:green)]($style)'

[conda]
style = "bg:green"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:green)]($style)'

[pixi]
style = "bg:green"
format = '[[ $symbol( $version)( $environment) ](fg:foreground bg:green)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:background"
format = '[[  $time ](fg:foreground bg:background)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:magenta)'
error_symbol = '[](bold fg:blue)'
vimcmd_symbol = '[](bold fg:magenta)'
vimcmd_replace_one_symbol = '[](bold fg:white)'
vimcmd_replace_symbol = '[](bold fg:white)'
