

[os]
disabled = false
style = "bg:green fg:foreground"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:green fg:foreground"
style_root = "bg:green fg:foreground"
format = '[ $user ]($style)'

[directory]
style = "fg:foreground bg:cyan"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "


[nodejs]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[c]
symbol = " "
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[cpp]
symbol = " "
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[rust]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[golang]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[php]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[java]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[kotlin]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[haskell]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[python]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:foreground bg:red)]($style)'

[docker_context]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $context) ](fg:#83a598 bg:green)]($style)'

[conda]
style = "bg:green"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:green)]($style)'

[pixi]
style = "bg:green"
format = '[[ $symbol( $version)( $environment) ](fg:foreground bg:green)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:background"
format = '[[  $time ](fg:foreground bg:background)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:magenta)'
error_symbol = '[](bold fg:blue)'
vimcmd_symbol = '[](bold fg:magenta)'
vimcmd_replace_one_symbol = '[](bold fg:white)'
vimcmd_replace_symbol = '[](bold fg:white)'
